name: Deploy Vue to S3 + CoudFront (OIDC)

on:
  push:
    branchas: ["master"]
  
env:
  BUILD_DIR: dist

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: build
        run: npm run build
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync assets (long cache)
        run: |
          aws s3 sync $BUILD_DIR s3://${{ secrets.S3_BUCKET }} \
            --delete \
            --exclude "index.html" \
            --cache-control "public,max-age=3153600,inmutable" \
            --only-show-errors
      
      - name: Upload index.html (no-store)
        run: |
          aws s3 cp $BUILD_DIR/index.html s3://${{ secrets.S3_BUCKET }}/index.html \
          --cache-control "no-store" \
          --content-type "text/html" \
          --only-show-errors

      - name: Invalidate CloudFront
        run: |
          aws cloudFront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths '/*'